#%RAML 1.0
title: Bumpy-Booby API
description: API to create, edit and delete issues.
version: v1.1.2
protocols: [ HTTP, HTTPS ]
baseUri: http://{Bumpy-Booby-URL}
mediaType: application/x-www-form-urlencoded

